<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>674dc1ba-9795-4154-b15a-a0aa71c62182</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-1749gbk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1dae725c-ecb6-4104-81f4-673744573c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29767798-1066-46fc-841e-e13b3ed08063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1749gbk</value>
      <webElementGuid>a3a92f0e-e16d-49f2-b5f1-9dc10ff53e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>전체화면 종료</value>
      <webElementGuid>21c93d7d-e3e7-4cd9-ae2c-495c899370ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-:r2s:&quot;)/footer[@class=&quot;chakra-modal__footer css-bxbe2i&quot;]/div[@class=&quot;chakra-stack css-13uls06&quot;]/div[@class=&quot;css-1de9ey7&quot;]/div[@class=&quot;chakra-stack css-1nkbehs&quot;]/div[@class=&quot;chakra-stack css-1igwmid&quot;]/button[@class=&quot;chakra-button css-1749gbk&quot;]</value>
      <webElementGuid>1046e081-4a1a-4d60-a79a-72883bdecbc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>0fb95f00-b2ce-4a7c-b7be-bfd10ed881b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:r2s:']/footer/div/div/div/div[2]/button</value>
      <webElementGuid>15353089-e955-486a-a8a3-f57d37b19171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='자'])[2]/following::button[3]</value>
      <webElementGuid>13971288-3700-4c9b-9d17-c29300d4b168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='로그아웃'])[1]/following::button[3]</value>
      <webElementGuid>e578e334-2ccc-4196-97d7-f914fe86495b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='포커스타임 시간을 줄입니다.'])[1]/preceding::button[1]</value>
      <webElementGuid>084c48f4-6d37-4ef9-8ce0-b1153b21cce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='전체화면 종료']/parent::*</value>
      <webElementGuid>9f7e9016-07da-4e5b-9485-aa070f07647f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div/div[2]/button</value>
      <webElementGuid>0fcf8bac-4eb7-485d-b4e5-0fd2a2cc02ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
