<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>e55ceb8b-8e1f-4959-9792-54c5b9341abf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-mhxgfw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d796211a-409b-496d-b28c-72ce3c6b127c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>615bbf4b-6b2a-4b9c-b981-60e9dedef800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-mhxgfw</value>
      <webElementGuid>086a4112-09f9-466b-a8ad-ec8377c219d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>modal-close-button</value>
      <webElementGuid>05fda9e9-a942-4bae-bc97-b5d8b5d34a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>닫기</value>
      <webElementGuid>5d81655c-de20-4e53-8af5-fc2f96a68674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:R6kvf5t5ufja:&quot;)/div[@class=&quot;chakra-stack css-11bebky&quot;]/button[@class=&quot;chakra-button css-mhxgfw&quot;]</value>
      <webElementGuid>03c77e9d-bdf9-4ea3-8806-2f73bd825e0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>a285b801-e20c-450a-9518-941e6320665a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:R6kvf5t5ufja:']/div[2]/button</value>
      <webElementGuid>84c19b18-aa4b-4b37-8932-a0487720031e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='다시 보지 않기'])[1]/following::button[1]</value>
      <webElementGuid>3d5289f9-ef3d-4de2-a0a3-8dd936aef995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='도와주세요'])[1]/following::button[1]</value>
      <webElementGuid>32343e0f-551d-4216-95a2-0ec6a6dcbc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='닫기']/parent::*</value>
      <webElementGuid>2dc29259-35dd-4913-be3c-ec58f576669e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>805399ae-86ab-44ea-bbca-8cc948bf6250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@data-testid = 'modal-close-button']</value>
      <webElementGuid>d35a3c28-aba5-49a5-be3a-7aca8929d0e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
