<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__AB7Lab Id5V1</name>
   <tag></tag>
   <elementGuidId>408fdedd-dfe4-47a5-bd1b-c3baf7dd1106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='i6']/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.AB7Lab.Id5V1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a65b6142-5e21-4ef8-ac14-4dfb236ebf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AB7Lab Id5V1</value>
      <webElementGuid>5aeeb440-16cd-4615-a924-172870075ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;i6&quot;)/div[@class=&quot;vd3tt&quot;]/div[@class=&quot;AB7Lab Id5V1&quot;]</value>
      <webElementGuid>35009e67-9a2e-479a-8aa0-65ffec65a8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/focuspangQ and A/Page_focuspang ai 3.0/iframe_</value>
      <webElementGuid>fe449d1c-ca6b-4a17-a8ea-79e98b8f618d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='i6']/div[3]/div</value>
      <webElementGuid>6390d286-cd66-445a-8af7-5a3756003c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[13]</value>
      <webElementGuid>80b5e153-d5c0-4d34-a584-6b61fb732c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='어떤 종류인지 선택해 주세요.'])[1]/following::div[13]</value>
      <webElementGuid>6fd36943-5de6-4149-8b3f-a1abebdf95a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='새 차트가 필요합니다.'])[1]/preceding::div[2]</value>
      <webElementGuid>c1af91a2-9cdc-41fa-bdbb-bf5929943c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='연수 신청합니다.'])[1]/preceding::div[11]</value>
      <webElementGuid>02c8f277-8ae7-4c34-93aa-e32b2f2a0ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div</value>
      <webElementGuid>8cdd850d-aee0-4841-af91-b722d1a9095c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
