<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_</name>
   <tag></tag>
   <elementGuidId>7d3e4313-6a2f-4a2b-a07f-a57524ecffa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>43745bb1-208f-40cc-b5db-b1a6684c28ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://docs.google.com/forms/d/e/1FAIpQLSeq0Q1F6ssdDzoMEiJQkcOvDUaWGsKiHyskA8xXKGVh88QGJw/viewform?embedded=true</value>
      <webElementGuid>3b1cb68b-ab75-4b26-9ef0-cee7cb711bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>351a8d94-8705-47a4-8cf9-7bad575dd78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>2bb4150b-12f3-4c9c-a96b-c94eaaf61435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>19e359f6-3348-47b5-b0d7-d964adc15e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로드 중…</value>
      <webElementGuid>b7874ec8-cc4f-44e7-8879-bc1d8f97a49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;inner&quot;]/div[1]/iframe[1]</value>
      <webElementGuid>91d10cba-0950-44ac-b12c-105feaf1a1b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/div/iframe</value>
      <webElementGuid>32926cf6-c304-4daa-8194-e5c5732b291b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Speedy Question and Answer'])[1]/following::iframe[1]</value>
      <webElementGuid>760f17dc-b747-4525-af80-87a7a7b97b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::iframe[1]</value>
      <webElementGuid>9a63afff-42f4-4123-89ad-6715fed77fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 3R Innovation Inc. All rights reserved.'])[1]/preceding::iframe[1]</value>
      <webElementGuid>6d63d1bb-7f7b-41f3-93dd-af99f4e164da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사업자등록번호 : 2459102274'])[1]/preceding::iframe[1]</value>
      <webElementGuid>091d39b0-3e3a-4be3-b817-08e09c2254b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='로드 중…']/parent::*</value>
      <webElementGuid>e3ecd5cb-691f-4265-853a-245d3afb1684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>89a66044-793a-494a-8f4a-2e762a182f55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://docs.google.com/forms/d/e/1FAIpQLSeq0Q1F6ssdDzoMEiJQkcOvDUaWGsKiHyskA8xXKGVh88QGJw/viewform?embedded=true']</value>
      <webElementGuid>329e635d-0747-4952-955b-688e1e16a37a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
