<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1_2_3</name>
   <tag></tag>
   <elementGuidId>ccfb2f2b-8b37-40f5-bbf2-cfbf0d6df1ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:r3u:']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1iiz02i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>56ce015e-6a25-4bf1-8ca7-5fca174fdaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>quizset-card</value>
      <webElementGuid>3cb4ad92-dbc0-4e2e-96a8-ca92134baf4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1iiz02i</value>
      <webElementGuid>11940d88-b304-4391-a433-7931f4533b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>퀴즈수업 중 이해도를 확인하는 간단한 퀴즈 만들기 </value>
      <webElementGuid>ec4fbbff-eafb-476e-ba7a-2c4170bb4f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:r3u:&quot;)/div[@class=&quot;chakra-stack css-1jery12&quot;]/div[@class=&quot;css-1iiz02i&quot;]</value>
      <webElementGuid>4bfc96a7-d3d3-48b4-b781-bbcd1a1b78b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r3u:']/div/div</value>
      <webElementGuid>b12c2d50-06f9-4a09-88a3-e7def5a2428a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='퀴즈'])[1]/following::div[18]</value>
      <webElementGuid>95327d7f-1587-4123-9687-11e1bc066f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='취소'])[1]/preceding::div[5]</value>
      <webElementGuid>4a1e88c5-3d87-4243-9122-430cdc6cf40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div</value>
      <webElementGuid>059e988d-ab04-40f6-8649-55c363912659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@data-testid = 'quizset-card']</value>
      <webElementGuid>5eb75b3d-1354-40aa-8c35-6965ea182094</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
