<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Kami sedang mempersiapkan pelayanan dalam_910166</name>
   <tag></tag>
   <elementGuidId>752cca1a-a18a-458c-8fb2-b05b3dd8003e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa-solid.fa-angle-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div/h1/button/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d8b30d01-62a2-479c-8ebf-987cd9faeeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-solid fa-angle-left</value>
      <webElementGuid>d8e4cb65-e402-4125-baa6-c4dd989fc8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d6f806b-2f18-44c5-9719-26fb2bf9707c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;inner&quot;]/h1[@class=&quot;major&quot;]/button[1]/i[@class=&quot;fa-solid fa-angle-left&quot;]</value>
      <webElementGuid>471fde57-f60f-4a1b-83bc-837ea41f3015</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/h1/button/i</value>
      <webElementGuid>367a4186-dd0e-46c0-8b2e-5f21927aa3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>43cd32bb-d02e-4f71-80d5-5dc30f1cd5ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
