<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Indonesian</name>
   <tag></tag>
   <elementGuidId>3dd6b346-fa55-4734-88ed-2a79ba335840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='kr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f773e0b8-a3f2-4c8c-a88a-8a8921064128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../indonesian/loading.html</value>
      <webElementGuid>5523d894-9b85-4aa3-8069-7bffb7a9d3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kr</value>
      <webElementGuid>4508bdae-aab3-469c-99c3-c485d0b6a437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesian</value>
      <webElementGuid>d23765ea-49a9-45f5-b8c3-e04292722cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;inner&quot;]/div[@class=&quot;dropdown&quot;]/a[@id=&quot;kr&quot;]</value>
      <webElementGuid>920556b2-5189-4087-973a-6194180eede6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='kr']</value>
      <webElementGuid>a4c69742-8166-4068-8ffd-e5c052ec07a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/div/a[2]</value>
      <webElementGuid>61e0501a-a7d8-428b-b7db-6586013d1064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Indonesian')]</value>
      <webElementGuid>89ecda59-6e76-407f-be9f-eaf7ecabf1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[2]</value>
      <webElementGuid>20751d69-676b-40a0-8fd5-e18ac6dfffc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Japanese'])[1]/preceding::a[1]</value>
      <webElementGuid>3ba05f6d-0396-4b09-af99-a4435625cb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Korean'])[1]/preceding::a[2]</value>
      <webElementGuid>d58e8139-b1c1-4a87-8a1f-7ed1264b1b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Indonesian']/parent::*</value>
      <webElementGuid>1c953b18-6059-4eba-9e27-b1d975334416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../indonesian/loading.html')]</value>
      <webElementGuid>cc921a23-8710-450e-9ea1-46f772cf86ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>9cc72964-35bd-4a05-9c04-ba19d1d281ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../indonesian/loading.html' and @id = 'kr' and (text() = 'Indonesian' or . = 'Indonesian')]</value>
      <webElementGuid>72d947b5-e8d2-4563-bacc-77e010923f5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
