<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__chakra-input css-1cjy4zv_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>56365edb-daf1-47a1-9a0f-f646dadfa246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.chakra-input.css-1cjy4zv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='www.naver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0110109-a2cc-4bb9-a08b-b1cb5e0cfa9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>링크 주소를 입력해주세요.</value>
      <webElementGuid>8a37c4e9-78ea-4595-9f64-a1abf72227f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1cjy4zv</value>
      <webElementGuid>a6200a6c-cc4e-4da8-8b1a-fbe81af97612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>www.naver</value>
      <webElementGuid>2f4c1883-b7af-4953-ae17-07df099fefb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-:r4p:--tabpanel-0&quot;)/div[@class=&quot;chakra-stack css-13uls06&quot;]/div[@class=&quot;chakra-stack css-1uodvt1&quot;]/input[@class=&quot;chakra-input css-1cjy4zv&quot;]</value>
      <webElementGuid>9dee1f84-611c-4f06-b417-ac49bdf25199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='www.naver']</value>
      <webElementGuid>6410dbba-05d6-4913-8f56-491e72426857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r4p:--tabpanel-0']/div/div/input</value>
      <webElementGuid>055748dd-bf57-420d-a589-f053d583d5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>cadab028-4d3b-4c66-a7e2-b9a05145905a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
