<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field-r52</name>
   <tag></tag>
   <elementGuidId>cdd84226-ff4e-46e1-85a2-a805d33c233c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-:r52:']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'filelink-title-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6889b196-07b4-41e9-8290-ee6b4b303936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>15b7b2f5-cbdb-4c7d-ae8e-af55ae22ec40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>링크 제목을 입력해주세요.</value>
      <webElementGuid>23bb7690-3528-4080-bdb6-d89f2a16237e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:r52:</value>
      <webElementGuid>3420f43c-2a62-4cb9-bd16-faebd8f7ab9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-597838</value>
      <webElementGuid>33a08c64-a6b0-4b83-83f2-d6a34d7b7e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4bfb0f4a-f20e-4728-96a0-033d6293848d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:r52:&quot;)</value>
      <webElementGuid>40f94f20-c7ef-4c8d-a4ba-f8b4dbfa6be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>filelink-title-input</value>
      <webElementGuid>65c3e60c-eef7-4041-9803-568cb6e2407d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-:r52:']</value>
      <webElementGuid>fa52591c-7205-45bb-87d1-d2dc7bd04950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r4p:--tabpanel-0']/div/div/div/div/input</value>
      <webElementGuid>e7bfb796-6b0d-4ccb-a7a3-6613cceab43b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>718b15dd-71a9-40f2-b153-b412782a70a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-:r52:']</value>
      <webElementGuid>3ee3e4a6-82e6-4bfb-87d9-67981041fb7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
