<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Quit_chakra-icon chakra-accordion__icon_d97f05</name>
   <tag></tag>
   <elementGuidId>97fbc729-1360-4978-bd6b-f1455a7d46d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.chakra-icon.chakra-accordion__icon.css-186l2rg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Quit'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'filelink-accordion-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>be1105a3-c622-42a0-a4e6-3652e7e24922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>4ab5fe2c-5de7-458d-b07b-900cc84be896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>38e7ebde-b088-45b0-bac0-28f8aad6198a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-icon chakra-accordion__icon css-186l2rg</value>
      <webElementGuid>9fc60a89-621f-47c7-891e-10a323d2307a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6490b3e8-cd47-4154-821e-6a85f3ead504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion-button-:r4n:&quot;)/div[@class=&quot;chakra-stack css-1igwmid&quot;]/svg[@class=&quot;chakra-icon chakra-accordion__icon css-186l2rg&quot;]</value>
      <webElementGuid>362cb09c-d5c3-47e2-8f07-1c313ccfb167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordion-button-:r4o:</value>
      <webElementGuid>8033ef55-eb07-4760-8e76-3b49ba247295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>filelink-accordion-button</value>
      <webElementGuid>38f38f55-c8a0-4e49-be0e-e813c5fbb61c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quit'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>8973c900-7121-4aaf-84fa-7b45999f00ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='를 할 수 있습니다.'])[1]/following::*[name()='svg'][6]</value>
      <webElementGuid>3d8424c5-3380-4803-8813-c8e91e0a5881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='학생에게 자료 공유하기'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>fb857842-130f-49bb-9dff-fee1053527fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='링크'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>2fdb9548-8262-4714-ac8f-7d51ef7cd1fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
