<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_weekdayoption</name>
   <tag></tag>
   <elementGuidId>b356cf3f-06ef-4202-80be-99ad33be2a31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='weekday']/option[@value='3']</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>수요일</value>
      <webElementGuid>5b84e164-cdf9-4a8a-9f62-4d7d0ef06565</webElementGuid>
   </webElementProperties>
</WebElementEntity>
