<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__subjectName</name>
   <tag></tag>
   <elementGuidId>b91b85c5-9aa1-49c1-a3eb-9e1362aef0fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subjectName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subjectName']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'subjectName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2792ce08-7116-480c-84c8-769c1eba26ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>7bde5b85-8398-455f-afa9-f7c7c08cf1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>추가하실 과목명을 입력해주세요</value>
      <webElementGuid>f40ed241-0884-4fc2-9c8e-6a6e19cde723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subjectName</value>
      <webElementGuid>92f762d2-012a-4246-8701-4b611c11fd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-mj3in7</value>
      <webElementGuid>d225680a-2469-42ed-904d-98dce3a95165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fce2bc81-04d8-435c-a68e-1fe3e668e6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>7b3a8498-ce6c-42e0-8108-1c64f29817c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subjectName&quot;)</value>
      <webElementGuid>726e9fa8-c481-4215-a6ae-f1704b03bcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>subjectName</value>
      <webElementGuid>b54cdfe2-a486-408b-8228-464abf0f7374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subjectName']</value>
      <webElementGuid>25d45696-6284-4de7-b58b-a4f4197eafe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r3a:']/div/div/div/div/div/input</value>
      <webElementGuid>ff3d7c36-855b-4ef1-a6eb-ba3b11af138e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0e4de2b4-4df5-452f-9448-71f208b977a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '추가하실 과목명을 입력해주세요' and @id = 'subjectName' and @type = 'text']</value>
      <webElementGuid>5438a60f-1235-4794-b204-d033d458467a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
