<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__clean-btn menu__caret_1</name>
   <tag></tag>
   <elementGuidId>7685fa9f-27a8-4800-ba2e-ea606d5f669b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.theme-doc-sidebar-item-category.theme-doc-sidebar-item-category-level-1.menu__list-item.menu__list-item--collapsed > div.menu__list-item-collapsible > button.clean-btn.menu__caret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;사이드바 분류 '학생용 포커스팡' 펼치기&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1e09d827-7cb6-4daf-8ce2-1f61df09fa6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>사이드바 분류 '학생용 포커스팡' 펼치기</value>
      <webElementGuid>495f3402-ed9d-428d-ae25-f06548b42f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5d525c59-9ded-4778-8b65-f4452ca33b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cbfb9b78-b3d9-4523-b11c-4ade77ccfabe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clean-btn menu__caret</value>
      <webElementGuid>c41d1dfe-4041-4375-8413-04b3bf31d4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__docusaurus_skipToContent_fallback&quot;)/div[@class=&quot;docsWrapper_hBAB&quot;]/div[@class=&quot;docRoot_UBD9&quot;]/aside[@class=&quot;theme-doc-sidebar-container docSidebarContainer_YfHR&quot;]/div[@class=&quot;sidebarViewport_aRkj&quot;]/div[@class=&quot;sidebar_njMd&quot;]/nav[@class=&quot;menu thin-scrollbar menu_SIkG&quot;]/ul[@class=&quot;theme-doc-sidebar-menu menu__list&quot;]/li[@class=&quot;theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed&quot;]/div[@class=&quot;menu__list-item-collapsible&quot;]/button[@class=&quot;clean-btn menu__caret&quot;]</value>
      <webElementGuid>2b6a8b40-162c-44e8-8069-6da2386fe0b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[6]</value>
      <webElementGuid>648edae1-1453-4e67-9abb-8660597b9843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus_skipToContent_fallback']/div/div/aside/div/div/nav/ul/li[3]/div/button</value>
      <webElementGuid>f0c3b914-c28e-48b6-b9db-4158dba12ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/button</value>
      <webElementGuid>dbdc11fc-714a-452c-8b81-946fb8e50abf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
