<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>file_share_button</name>
   <tag></tag>
   <elementGuidId>14fe39a2-33a5-4b3a-903a-5d32e0a7f5b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'filelink-file-button']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tabs-:r5k:--tabpanel-1&quot;]/div/div[1]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>28653205-3994-4398-948d-cf568faf00c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fbf22080-d6e4-4d54-b575-a0f7c9ae1734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-10qoo3g</value>
      <webElementGuid>b8d3e6d3-4a1f-4c59-b78a-8502fc01189e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>파일 공유</value>
      <webElementGuid>81f8ddb9-4141-43ff-833a-a39024074fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-:r5j:--tabpanel-1&quot;)/div[@class=&quot;chakra-stack css-13uls06&quot;]/div[@class=&quot;chakra-stack css-1uodvt1&quot;]/button[@class=&quot;chakra-button css-10qoo3g&quot;]</value>
      <webElementGuid>f7cb2473-cb98-4c53-aa36-eefe3f382224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>filelink-file-button</value>
      <webElementGuid>da8ee8ef-2173-4987-af0d-ca270df48f81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[17]</value>
      <webElementGuid>7a98865f-3938-4b5b-8c0d-6fbb086d5775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-:r5j:--tabpanel-1']/div/div/button</value>
      <webElementGuid>5a63cd40-092a-40f7-ade1-80ed75c8b055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='링크 공유'])[1]/following::button[1]</value>
      <webElementGuid>f5ab0703-9c92-4dfd-a4e8-1c496f94c5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='파일'])[1]/following::button[2]</value>
      <webElementGuid>2ee81d86-a00b-47ad-b8e7-bd20d0ce32c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='학생의 사용을 통제할 앱과 웹 사이트'])[1]/preceding::button[1]</value>
      <webElementGuid>a0e29336-19d8-46f6-80f2-d08c98acb3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='앱/웹 제어 설정 추가'])[1]/preceding::button[2]</value>
      <webElementGuid>b6b6ef0d-63cf-4f92-bf3d-84b09f51527d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='파일 공유']/parent::*</value>
      <webElementGuid>4c088f55-795d-4812-b45a-e7a31e8ab1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/button</value>
      <webElementGuid>be25974a-1aa2-4a61-bf69-bf175fca5cc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
