<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field-r42</name>
   <tag></tag>
   <elementGuidId>1658176b-25a8-452d-9206-7630dca67f3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-:r42:']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'quiz-header-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d28d9919-daab-489e-b8d1-2f565885260e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>5b419fdd-f832-44e8-a6b9-ead912fab725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>예: 다음 중 옳지 않은 것은?</value>
      <webElementGuid>144f94d3-f5b3-4333-bfde-9c97f35d1c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>quiz-header-input</value>
      <webElementGuid>5a364152-f509-455c-8ca7-879a679c4712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:r42:</value>
      <webElementGuid>383b7481-10aa-4d7c-b32a-341f6c7db129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-mj3in7</value>
      <webElementGuid>9c697041-b589-49f7-a941-79fb7f1fa46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81f24cae-6c0c-4fa4-81fc-e5b1617e3d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:r42:&quot;)</value>
      <webElementGuid>ad0abf84-3cb8-423f-8577-160fcfc779aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-:r42:']</value>
      <webElementGuid>caf68037-1d18-4fab-b7f6-2f95850a7ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>d0ec8034-547e-4c4d-acfd-cfe941f508dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '예: 다음 중 옳지 않은 것은?' and @data-testid = 'quiz-header-input' and @id = 'field-:r42:' and @type = 'text']</value>
      <webElementGuid>f506eafa-046d-4cfb-b9e9-bf0c1a3976e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
