<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1 - 1  71e a8c 71     changwu_rhimfocus_606c12</name>
   <tag></tag>
   <elementGuidId>32deeaba-ff99-4235-bd59-eab96eb7ffc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.chakra-container.css-10wiq0h</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>911bec02-d877-4202-9247-a683b0a9f1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-container css-10wiq0h</value>
      <webElementGuid>86d45ae0-62f3-408f-ba4b-1abc29741008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 - 1자동화테스트학생 초대 코드71e a8c 71처음으로수업 공지포커스 타임퀴즈팡과제 관리대시보드학생 명단모둠 활동임임창우changwu_rhim@focuspang.com설정로그아웃과제 관리새 과제 등록Back과제 공개 일시즉시예약제출 기한*공지할 반 추가하기과제 테스트첨부파일 목록취소등록</value>
      <webElementGuid>0401cbf7-b1b6-44a5-9699-1e394958ecfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_d65c78 chakra-ui-light&quot;]/div[@class=&quot;css-wrghvn&quot;]/div[@class=&quot;chakra-container css-10wiq0h&quot;]</value>
      <webElementGuid>57378940-326a-4446-bc84-37546153afc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>80e57a50-ec61-4a1b-95f2-7570232367be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
