<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__subjectName</name>
   <tag></tag>
   <elementGuidId>b91b85c5-9aa1-49c1-a3eb-9e1362aef0fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#subjectName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='subjectName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c2662a7-eb0c-44e3-8caf-d1158c413a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>aadfecf9-3af3-4dff-9e3e-6778a56bf525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>추가하실 과목명을 입력해주세요</value>
      <webElementGuid>c1e24ef0-1f31-476e-88ee-7e35c7165ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subjectName</value>
      <webElementGuid>119d6bec-d7e8-4d28-bcec-63049e38e902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-mj3in7</value>
      <webElementGuid>5a0f68ce-370f-4ee5-ad88-a17070eaf78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c20e05f-e0b7-444f-9d2f-8de038f1cc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>4835b9d3-1228-4c91-aff1-4e13be03223e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subjectName&quot;)</value>
      <webElementGuid>32b4a4e5-6e64-4db9-845c-65368d580ecf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='subjectName']</value>
      <webElementGuid>d4df58a5-f89c-4541-99f7-3d5051423c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r3a:']/div/div/div/div/div/input</value>
      <webElementGuid>4ae9802a-78bc-48a7-8506-6d631dd81bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c926f548-d0ce-465c-8ac1-17dbc33f7dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '추가하실 과목명을 입력해주세요' and @id = 'subjectName' and @type = 'text']</value>
      <webElementGuid>06692bf4-d719-453d-b563-3ce2c849150c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
