<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field-r3u</name>
   <tag></tag>
   <elementGuidId>7941d366-3607-4315-8eab-0e9fc88525a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-\:re\:</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-:r3u:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e586fc52-27a5-4cc8-ae7e-35e64094f971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>5fa9ede2-49a5-4733-ab39-d34d63c27d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>만드실 퀴즈의 제목을 입력하세요. (최대 45자)</value>
      <webElementGuid>6a2375f3-7fad-4d0a-9423-47387b6eeee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:r3u:</value>
      <webElementGuid>4d6f53cf-4b07-4877-9d93-5b561e58fd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-mj3in7</value>
      <webElementGuid>fd6eb77d-6d3f-46ef-a7a5-a47332c3b8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a63ea376-d241-4b78-a228-4619493e54ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>w</value>
      <webElementGuid>905bb4f8-c5be-4222-afaa-5356d71533cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:r3u:&quot;)</value>
      <webElementGuid>2ba2735f-1d0a-4cc4-ba63-74bb6ca7e05a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-:r3u:']</value>
      <webElementGuid>154e58d1-f1ae-4163-bd4f-5b6d22881919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>591b4dd7-8091-4fd4-bd41-4387888edab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '만드실 퀴즈의 제목을 입력하세요. (최대 45자)' and @id = 'field-:r3u:' and @type = 'text']</value>
      <webElementGuid>d0fd2902-9f12-4e60-a8dd-966bdcf77bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
