<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__field-r3v</name>
   <tag></tag>
   <elementGuidId>41c4a6b4-4a17-428b-a4ea-ca4a4e9bd618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-\:r48\:</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>#field-\:r48\:</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdceddb2-ff03-4f63-95c7-5cfc7bd54d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>9db718b5-810c-468d-9b9c-aeddd7f8c182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>예: 다음 중 옳지 않은 것은?</value>
      <webElementGuid>a5a23555-eac1-4b9d-80f5-ef3bbb9a8a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:r3v:</value>
      <webElementGuid>71f306e7-6aec-4b6a-b4a1-c9415cf8780e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-mj3in7</value>
      <webElementGuid>efb356c3-b715-41d9-828c-0e937f57b871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1685b0df-7f75-4207-91e4-55874aa145ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-:r3v:&quot;)</value>
      <webElementGuid>5ca129a9-0868-4bff-90eb-c5e6d389a39a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-:r3v:']</value>
      <webElementGuid>0038a5f2-e2a5-45e7-89f4-b157e587c52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>dbb17628-170a-4968-a461-855df9558bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '예: 다음 중 옳지 않은 것은?' and @id = 'field-:r3v:' and @type = 'text']</value>
      <webElementGuid>e118aa92-4bfa-4126-8a9c-ed459b021d0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
