<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_</name>
   <tag></tag>
   <elementGuidId>4c97952a-3ce5-4541-8288-48ee31e940b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.chakra-stack.css-11ehgu5 > label.chakra-checkbox.css-8efisn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chakra-modal--body-:R7kvf5t5ufja:']/footer/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9b55bd96-fd82-460a-9e88-4060eb23dd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-checkbox css-8efisn</value>
      <webElementGuid>c8208cc8-b5e1-436b-97bc-99a0a83578fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>dont-show-checkbox</value>
      <webElementGuid>9a5b0fd3-4809-4707-bee5-2bb61eb58c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>다시 보지 않기</value>
      <webElementGuid>46167fc2-e99c-47a3-a8ea-fe6839fdbef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal--body-:R7kvf5t5ufja:&quot;)/footer[@class=&quot;chakra-modal__footer css-16ltw6x&quot;]/div[@class=&quot;chakra-stack css-11ehgu5&quot;]/label[@class=&quot;chakra-checkbox css-8efisn&quot;]</value>
      <webElementGuid>9ee92567-015e-4976-a934-0704288a780a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:R7kvf5t5ufja:']/footer/div/label</value>
      <webElementGuid>275f55c8-40f9-4c75-9070-fda2a6d352be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='기기 부팅 후 일정 시간이 지나면 꺼지며 Android 팩토리 모드로 진입하는 현상'])[1]/following::label[1]</value>
      <webElementGuid>befd9969-a8aa-4608-a61d-56ea7f9fceb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='굿노트와 같은 특정 앱의 사용 불가 현상'])[1]/following::label[1]</value>
      <webElementGuid>949810aa-f0d7-4f81-ad6d-24b82bdf6eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='닫기'])[2]/preceding::label[1]</value>
      <webElementGuid>df66bfae-d210-481f-a65e-4938174a3884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/label</value>
      <webElementGuid>25ef06c2-871e-411d-b1b8-a330f78b476e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '다시 보지 않기' or . = '다시 보지 않기')]</value>
      <webElementGuid>6cde6898-e32d-4a66-a47e-d10bcd5ba26e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
