<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>ba6f5fe6-fab7-4f0a-a48b-ab8fa9f64943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#weekday-0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='weekday-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1d58a823-f96e-436f-bc77-a4907df3b365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weekday-0-0</value>
      <webElementGuid>76c09d6e-8e0e-467f-b0ed-f3cc4bf894ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-1rli9xt</value>
      <webElementGuid>3d9dc59a-4578-4496-8ecc-57beb490c646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>월요일화요일수요일목요일금요일</value>
      <webElementGuid>84531366-b0e0-4795-8b2e-719ba688cefb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weekday-0-0&quot;)</value>
      <webElementGuid>1d72550e-e05c-4443-b45c-3f46b09650e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='weekday-0-0']</value>
      <webElementGuid>7a50a150-e0bd-4863-aea1-ad09432de4cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r3a:']/div/div[2]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>65e147c8-0fcf-49d0-9a4c-dd00a1c9ea11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='요일'])[1]/following::select[1]</value>
      <webElementGuid>03eed59e-23ec-48c7-9c95-112d6caea18b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='교시'])[1]/preceding::select[1]</value>
      <webElementGuid>be817543-c549-406b-8d39-83e9daaf1c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='수업 시간 추가하기'])[1]/preceding::select[2]</value>
      <webElementGuid>ad60260c-b75b-41b0-aef9-f57fe002fc80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>e78ad3a5-0389-48e6-8a05-0e1cd1e7f4c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'weekday-0-0' and (text() = '월요일화요일수요일목요일금요일' or . = '월요일화요일수요일목요일금요일')]</value>
      <webElementGuid>abe90297-48fc-4add-84cc-eed0b51f37ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
