<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_</name>
   <tag></tag>
   <elementGuidId>c1230e22-7b2c-49a8-b144-3a619b3b9b5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main']/div/div/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7a6ff39c-f170-47db-92ad-a821e08d5e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://docs.google.com/forms/d/e/1FAIpQLSeq0Q1F6ssdDzoMEiJQkcOvDUaWGsKiHyskA8xXKGVh88QGJw/viewform?embedded=true</value>
      <webElementGuid>b8ade976-3192-42b3-a4de-3b475dae5f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>43c8ac01-a2d3-4a83-97b7-ebf161fd31c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>361b06aa-6615-4d96-9fa2-9972ef2b5ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e0d35173-ba53-4854-8c70-b75990c05e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>로드 중…</value>
      <webElementGuid>992438a2-8eff-4b6b-aac1-515ff32d4709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;inner&quot;]/div[1]/iframe[1]</value>
      <webElementGuid>569df5aa-ab63-4342-9c8e-c559dfabe50f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main']/div/div/iframe</value>
      <webElementGuid>84533b2b-8907-4829-b98e-0b5238627946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Speedy Question and Answer'])[1]/following::iframe[1]</value>
      <webElementGuid>07a90240-9a06-433f-944f-5b16d4ed84a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::iframe[1]</value>
      <webElementGuid>00a3c5a6-f679-4eac-a423-9e4e948f796b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 3R Innovation Inc. All rights reserved.'])[1]/preceding::iframe[1]</value>
      <webElementGuid>1fc1b416-f7e9-418b-b0ad-7ded32e1098e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='사업자등록번호 : 2459102274'])[1]/preceding::iframe[1]</value>
      <webElementGuid>2bc9cf95-4cf2-4416-9f37-c897fe47eeec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='로드 중…']/parent::*</value>
      <webElementGuid>68c86508-d152-4863-91d6-16f6c2f24e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f80504dc-cc8d-45aa-b963-d42b02114834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://docs.google.com/forms/d/e/1FAIpQLSeq0Q1F6ssdDzoMEiJQkcOvDUaWGsKiHyskA8xXKGVh88QGJw/viewform?embedded=true' and (text() = '로드 중…' or . = '로드 중…')]</value>
      <webElementGuid>fef3992a-d18d-415b-8e88-053409a60134</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
