<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>2ff433f0-cae3-4c73-8f5f-edbd38837fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='weekday-0-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#weekday-0-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f136295e-514e-443d-9b85-84f51c8d0f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>weekday-0-0</value>
      <webElementGuid>bd1159de-7cad-4a59-889d-982ec2cf8302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weekday-0-0</value>
      <webElementGuid>5dc63afa-db6a-4efc-a659-2ce7810f0afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-select css-1rli9xt</value>
      <webElementGuid>e9ad738e-1ab9-4af6-becf-d117b7b4c517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>월요일화요일수요일목요일금요일</value>
      <webElementGuid>b8685646-e8ec-495b-8273-c9f4abaf1912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weekday-0-0&quot;)</value>
      <webElementGuid>cfc53d48-56c6-4351-a16f-3798e9ee434c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='weekday-0-0']</value>
      <webElementGuid>034d10fd-92e8-4f2c-ae1c-d3ebe98af01f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chakra-modal--body-:r3a:']/div/div[2]/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>5518466d-cf36-4a74-9c78-1925509ead16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='요일'])[1]/following::select[1]</value>
      <webElementGuid>88a3e314-c0d2-4b86-9e3e-e83af8e12354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='교시'])[1]/preceding::select[1]</value>
      <webElementGuid>17bd83c8-88d9-4946-8e15-e98307849921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='수업 시간 추가하기'])[1]/preceding::select[2]</value>
      <webElementGuid>8d15e084-adc8-4682-b81e-fd1ae363d7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>e7cf1ef1-55d4-4ed6-bc78-104a49265750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@data-testid = 'weekday-0-0' and @id = 'weekday-0-0']</value>
      <webElementGuid>0fe660b2-7940-43e3-aac6-ad0e4825b2d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
