<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile_image</name>
   <tag></tag>
   <elementGuidId>31aea120-c647-4d9a-843a-f8b6d959a7c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.chakra-avatar.css-10y9l5i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='회원 정보 수정'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4bd43467-eb1d-4dbe-9848-82d5a67f2c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>profile-image</value>
      <webElementGuid>1f49f030-d392-496a-93f2-42c3f97cfb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-avatar css-10y9l5i</value>
      <webElementGuid>ddb6466f-0823-4bcf-adf0-55e00344b7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>자</value>
      <webElementGuid>f6d84f21-201d-40f0-bc5a-3a267b6b9dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_d65c78 chakra-ui-light&quot;]/div[@class=&quot;css-wrghvn&quot;]/div[@class=&quot;chakra-container css-10wiq0h&quot;]/div[@class=&quot;css-1mc2bby&quot;]/div[@class=&quot;css-10ft286&quot;]/div[@class=&quot;chakra-container css-w8e4xc&quot;]/div[@class=&quot;chakra-stack css-153vwuu&quot;]/div[@class=&quot;chakra-stack css-1igwmid&quot;]/div[@class=&quot;chakra-stack css-ppmla1&quot;]/div[@class=&quot;chakra-stack css-1s86945&quot;]/div[@class=&quot;chakra-stack css-boo8w5&quot;]/div[@class=&quot;chakra-stack css-rql7r4&quot;]/span[@class=&quot;chakra-avatar css-10y9l5i&quot;]</value>
      <webElementGuid>c76dde64-654e-41b1-9454-9425e5b5d259</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='회원 정보 수정'])[1]/following::span[1]</value>
      <webElementGuid>b582088f-d4cf-495f-ade3-fbeeb894996e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='로그아웃'])[1]/following::span[2]</value>
      <webElementGuid>fbcca57a-66ee-47a4-a6a4-931d9089266c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='이름'])[1]/preceding::span[1]</value>
      <webElementGuid>d9674229-2ccb-4d3b-8c92-bdba70f7a02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span</value>
      <webElementGuid>c676a87e-0a3a-4f43-8fb0-d620e8286c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@data-testid = 'profile-image']</value>
      <webElementGuid>a0170785-9a1e-41bd-9a50-67b020818c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
