<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>등록버튼</description>
   <name>submitAt_input</name>
   <tag></tag>
   <elementGuidId>5151d4bb-6684-4bed-b87f-5d9026820edf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;field-:rv:&quot;]&#xd;
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'submit-at-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>387ac776-5279-49b4-901e-18bf7c4ec336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>submit-at-input</value>
      <webElementGuid>99405a3a-5c3f-4faa-b4fd-75585a3d6f12</webElementGuid>
   </webElementProperties>
</WebElementEntity>
