<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YourInputField</name>
   <tag></tag>
   <elementGuidId>8534f0ad-0730-463f-93d8-0b0a77f38da5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-\:rv\:&#xd;
</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;field-:r4h:&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;field-:rv:&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b687b3e1-f6a4-4ac9-9b37-c5dd31c2497f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-:rv:</value>
      <webElementGuid>d873f068-34f6-4f7b-a3fd-4b4fa6a92704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc8bb5de-65a3-44f5-bcce-e2c2fc95dad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-input css-1cjy4zv</value>
      <webElementGuid>236a78e2-4947-49aa-9ca2-01ff64867315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>datetime-local</value>
      <webElementGuid>821f1281-feed-4779-b5b9-42bef286abd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NaN-NaN-NaNTNaN:NaN</value>
      <webElementGuid>3afde138-7bc4-4a55-b5a3-d71a8012f103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;field-:rv:&quot;]</value>
      <webElementGuid>261b598d-b909-44ab-89df-a451d817a827</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-:rv:']</value>
      <webElementGuid>9af84da5-9942-4957-88cc-55909d5383d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>0b21dd55-b633-4a63-9bbc-690252e2e0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'field-:rv:']</value>
      <webElementGuid>1184d8de-b709-4e05-adab-80ab6bb20327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
