<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1_2_3_4</name>
   <tag></tag>
   <elementGuidId>0152fc0b-b28e-45ad-b834-e62fdd210ff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;chakra-modal-:rci:&quot;]/footer/div/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.chakra-button.css-1749gbk</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;chakra-modal-:r3c:&quot;)/footer[@class=&quot;chakra-modal__footer css-bxbe2i&quot;]/div[@class=&quot;chakra-stack css-13uls06&quot;]/div[@class=&quot;css-1de9ey7&quot;]/div[@class=&quot;chakra-stack css-1nkbehs&quot;]/div[@class=&quot;chakra-stack css-1igwmid&quot;]/button[@class=&quot;chakra-button css-1749gbk&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f96b8371-39b4-4c44-b486-41c193e3ae68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c061c8db-beb6-4231-9132-f72c3201d026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chakra-button css-1749gbk</value>
      <webElementGuid>51127776-cb9c-401b-bc21-3bc8af4b275e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>close-button</value>
      <webElementGuid>479e1859-b874-4c63-bc38-b003a3e0cd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 전체화면 닫기</value>
      <webElementGuid>56ea106c-ac4e-4c3b-ae76-53874e818e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chakra-modal-:r3c:&quot;)/footer[@class=&quot;chakra-modal__footer css-bxbe2i&quot;]/div[@class=&quot;chakra-stack css-13uls06&quot;]/div[@class=&quot;css-1de9ey7&quot;]/div[@class=&quot;chakra-stack css-1nkbehs&quot;]/div[@class=&quot;chakra-stack css-1igwmid&quot;]/button[@class=&quot;chakra-button css-1749gbk&quot;]</value>
      <webElementGuid>ae78902d-0ff2-4c1c-a22a-c0e364dab6cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>eca32bbf-f7d9-4328-81b2-9fb19f5d7c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='chakra-modal-:r3c:']/footer/div/div/div/div[2]/button</value>
      <webElementGuid>85e0080a-3ad2-4ce6-b315-a4bae07e7239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='로그아웃'])[1]/following::button[3]</value>
      <webElementGuid>07d45402-dac7-4d39-9642-62d4ffa305fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='설정'])[1]/following::button[4]</value>
      <webElementGuid>f56eb122-e3b2-4ec5-928e-dc88e1930684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='포커스타임 시간을 줄입니다.'])[1]/preceding::button[1]</value>
      <webElementGuid>ebc524fb-67e8-47f5-821b-71bb92b56760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='전체화면 닫기']/parent::*</value>
      <webElementGuid>d431989b-b1f6-4945-b424-f86003f64a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div/div[2]/button</value>
      <webElementGuid>6d17588b-d601-460e-a993-bf9d22cde3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@data-testid = 'close-button']</value>
      <webElementGuid>e7ec6543-8085-423f-9361-de2bde3902bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
